### ISSUE TITLE
Hello! Not an issue, just a question.

### ISSUE THREAD

**Issue by abclution** [Olipro/VMG1312-B10A#1]
There have been several releases of firmware since this particular version. 

How did you get the source code for this to begin with?

I would like to do an analysis of source code changes in the last few releases for this modem and don't really know where to get the source code. :)

**Comment by Olipro** [comment]
I wrote to Zyxel via their GPL compliance webpage providing the serial number and other details of my modem.

They then responded by e-mail with links to the code.
